import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "../components/ui/tooltip";
import { GridPattern } from "../components/magicui/gridPattern";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BioCraft",
  description: "Generated by create next app",
  icons: "/iconfoxit.png", 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon */}
        <link rel="icon" type="image/png" href="/icons/iconfoxit.png" />

        {/* Apple Touch Icons for iOS */}
        <link rel="apple-touch-icon" sizes="192x192" href="/icons/iconfoxit.png" />
        <link rel="apple-touch-icon" sizes="512x512" href="/icons/iconfoxit.png" />

        {/* Web App Manifest */}
        <link rel="manifest" href="/manifest.json" />

        {/* iOS meta tags */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

        {/* Theme color */}
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        < GridPattern width={40} height={40} className="-z-10 opacity-85"/>
        <TooltipProvider delayDuration={150}>
          {children}
        </TooltipProvider>
      </body>
    </html>
  );
}
